import {Platform, StyleSheet} from 'react-native';
import {
  screenWidth,
  screenHeight,
  fonts,
  fontSizes,
  screenScale,
} from '../../constants/constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fbfafa',
    justifyContent: 'flex-start',
    alignItems: 'center',
    opacity: 0.96,
  },
  imageBg: {
    width: screenWidth,
    height: screenHeight * 0.2,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  headerContainer: {
    width: screenWidth * 0.9,
    height: screenHeight * 0.15,
    marginTop: screenHeight * 0.03,
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontFamily: fonts.Rubik,
    fontSize: fontSizes.h9,
    fontWeight: '400',
    color: '#13231B',
  },
  headerContent: {
    fontFamily: fonts.RubikMedium,
    fontWeight: '500',
    fontSize: fontSizes.h4,
    color: '#13231B',
  },
  inputContainer: {
    width: screenWidth * 0.9,
    height: screenScale * 90,
    backgroundColor: '#fff',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingLeft: 10,
  },
  upgradeContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    flex: 1,
    backgroundColor: 'transparent',
    borderRadius: 10,
    fontFamily: fonts.Rubik,
    fontWeight: '400',
    fontSize: fontSizes.h12,
    color: 'black',
    paddingLeft: 15,
    opacity: 0.5,
  },
  upgradeBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: screenWidth * 0.9,
    backgroundColor: '#24201A',
    borderRadius: 10,
    marginTop: 20,
    padding: 10,
  },
  upgradeBtnTitle: {
    fontFamily: fonts.SfProBold,
    fontWeight: '700',
    fontSize: fontSizes.h10,
    color: '#fff',
  },
  upgradeBtnContent: {
    fontFamily: fonts.SfProMedium,
    fontWeight: '600',
    fontSize: fontSizes.h11,
    color: '#fff',
  },
  questions: {
    width: screenWidth * 0.9,
    height: screenHeight * 0.25,
    backgroundColor: '#fbfafa',
    borderRadius: 10,
    marginTop: 20,
  },
  categories: {
    width: screenWidth * 0.9,
    height: screenHeight * 0.5,
    borderRadius: 10,
    marginTop: 10,
  },
  questionsTitle: {
    fontFamily: fonts.Rubik,
    fontWeight: '700',
    fontSize: fontSizes.h11,
    color: '#13231B',
    marginLeft: 10,
    marginTop: 10,
  },
});
